# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ECE385/ECElab6/ECElab6.srcs/sources_1/bd/blazeit420/ip/blazeit420_dlmb_v10_0/blazeit420_dlmb_v10_0.xci
# IP: The module: 'blazeit420_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE385/ECElab6/ECElab6.gen/sources_1/bd/blazeit420/ip/blazeit420_dlmb_v10_0/blazeit420_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blazeit420_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/ECE385/ECElab6/ECElab6.srcs/sources_1/bd/blazeit420/ip/blazeit420_dlmb_v10_0/blazeit420_dlmb_v10_0.xci
# IP: The module: 'blazeit420_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE385/ECElab6/ECElab6.gen/sources_1/bd/blazeit420/ip/blazeit420_dlmb_v10_0/blazeit420_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blazeit420_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
