# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab6provided1/mb_intro_top.xdc

# Block Designs: bd/blazeit420/blazeit420.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420 || ORIG_REF_NAME==blazeit420} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_microblaze_0_1/blazeit420_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_microblaze_0_1 || ORIG_REF_NAME==blazeit420_microblaze_0_1} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_dlmb_v10_0/blazeit420_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_dlmb_v10_0 || ORIG_REF_NAME==blazeit420_dlmb_v10_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_ilmb_v10_0/blazeit420_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_ilmb_v10_0 || ORIG_REF_NAME==blazeit420_ilmb_v10_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_dlmb_bram_if_cntlr_0/blazeit420_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==blazeit420_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_ilmb_bram_if_cntlr_0/blazeit420_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==blazeit420_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_lmb_bram_0/blazeit420_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_lmb_bram_0 || ORIG_REF_NAME==blazeit420_lmb_bram_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_xbar_0/blazeit420_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_xbar_0 || ORIG_REF_NAME==blazeit420_xbar_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_microblaze_0_axi_periph_0/blazeit420_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_microblaze_0_axi_periph_0 || ORIG_REF_NAME==blazeit420_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_microblaze_0_axi_intc_0/blazeit420_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_microblaze_0_axi_intc_0 || ORIG_REF_NAME==blazeit420_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_mdm_1_0/blazeit420_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_mdm_1_0 || ORIG_REF_NAME==blazeit420_mdm_1_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_clk_wiz_1_0/blazeit420_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_clk_wiz_1_0 || ORIG_REF_NAME==blazeit420_clk_wiz_1_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_rst_clk_wiz_1_100M_0/blazeit420_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==blazeit420_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_axi_gpio_0_0/blazeit420_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_axi_gpio_0_0 || ORIG_REF_NAME==blazeit420_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_axi_uartlite_0_0/blazeit420_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_axi_uartlite_0_0 || ORIG_REF_NAME==blazeit420_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_axi_gpio_1_0/blazeit420_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_axi_gpio_1_0 || ORIG_REF_NAME==blazeit420_axi_gpio_1_0} -quiet] -quiet

# IP: bd/blazeit420/ip/blazeit420_axi_gpio_2_0/blazeit420_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blazeit420_axi_gpio_2_0 || ORIG_REF_NAME==blazeit420_axi_gpio_2_0} -quiet] -quiet

# XDC: d:/ECE385/ECElab6/ECElab6.gen/sources_1/bd/blazeit420/blazeit420_ooc.xdc
